import uuid
import os
import sys
from pathlib import Path

# Add the backend directory to the path so we can import from app
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from db.database import add_restaurant, get_restaurant
import uuid

restaurants = [
    {
        "id": str(uuid.uuid4()),
        "name": "Spice Route",
        "location": "Cyber City",
        "cuisine": "North Indian",
        "total_capacity": 80,
        "opening_time": "12:00",
        "closing_time": "23:30",
        "description": "Authentic North Indian cuisine with traditional tandoor dishes and rich gravies.",
        "latitude": 28.4949,
        "longitude": 77.0869,
        "email": "info@spiceroute.com",
        "phone": "+91-124-456-7890",
        "website": "https://spiceroute.example.com",
        "address": "DLF Phase 2, Cyber City, Gurgaon",
        "city": "Gurgaon"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Saravana Bhavan",
        "location": "T. Nagar",
        "cuisine": "South Indian",
        "total_capacity": 120,
        "opening_time": "06:00",
        "closing_time": "22:00",
        "description": "Traditional South Indian vegetarian restaurant famous for dosas and filter coffee.",
        "latitude": 13.0418,
        "longitude": 80.2341,
        "email": "contact@saravanabhavan.com",
        "phone": "+91-44-2834-5678",
        "website": "https://saravanabhavan.example.com",
        "address": "Usman Road, T. Nagar, Chennai",
        "city": "Chennai"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Toit Brewpub",
        "location": "Indiranagar",
        "cuisine": "Continental",
        "total_capacity": 150,
        "opening_time": "12:00",
        "closing_time": "01:00",
        "description": "Craft brewery with wood-fired pizzas and continental cuisine in a vibrant atmosphere.",
        "latitude": 12.9784,
        "longitude": 77.6408,
        "email": "hello@toit.in",
        "phone": "+91-80-4112-3456",
        "website": "https://toit.example.com",
        "address": "100 Feet Road, Indiranagar, Bengaluru",
        "city": "Bengaluru"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "German Bakery",
        "location": "Koregaon Park",
        "cuisine": "European",
        "total_capacity": 60,
        "opening_time": "08:00",
        "closing_time": "23:00",
        "description": "Iconic bakery serving fresh breads, pastries, and European dishes since 1988.",
        "latitude": 18.5362,
        "longitude": 73.8980,
        "email": "info@germanbakery.com",
        "phone": "+91-20-2613-4567",
        "website": "https://germanbakery.example.com",
        "address": "North Main Road, Koregaon Park, Pune",
        "city": "Pune"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Paradise Biryani",
        "location": "Secunderabad",
        "cuisine": "Hyderabadi",
        "total_capacity": 200,
        "opening_time": "11:00",
        "closing_time": "23:30",
        "description": "Legendary restaurant serving authentic Hyderabadi biryani and kebabs since 1953.",
        "latitude": 17.4399,
        "longitude": 78.4983,
        "email": "orders@paradisebiryani.com",
        "phone": "+91-40-2784-5678",
        "website": "https://paradisebiryani.example.com",
        "address": "MG Road, Secunderabad, Hyderabad",
        "city": "Hyderabad"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Trishna",
        "location": "Fort",
        "cuisine": "Seafood",
        "total_capacity": 45,
        "opening_time": "19:00",
        "closing_time": "23:30",
        "description": "Award-winning seafood restaurant with contemporary Indian coastal cuisine.",
        "latitude": 18.9322,
        "longitude": 72.8264,
        "email": "reservations@trishna.com",
        "phone": "+91-22-2270-3213",
        "website": "https://trishna.example.com",
        "address": "Sai Baba Street, Fort, Mumbai",
        "city": "Mumbai"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Farzi Cafe",
        "location": "DLF Mall",
        "cuisine": "Modern Indian",
        "total_capacity": 90,
        "opening_time": "12:00",
        "closing_time": "00:30",
        "description": "Modern Indian bistro with molecular gastronomy and innovative presentations.",
        "latitude": 28.4744,
        "longitude": 77.1025,
        "email": "gurgaon@farzicafe.com",
        "phone": "+91-124-467-8901",
        "website": "https://farzicafe.example.com",
        "address": "DLF Mall of India, Sector 18, Gurgaon",
        "city": "Gurgaon"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Dakshin",
        "location": "Express Avenue",
        "cuisine": "South Indian",
        "total_capacity": 85,
        "opening_time": "12:30",
        "closing_time": "15:00",
        "description": "Fine dining South Indian restaurant showcasing regional cuisines from four southern states.",
        "latitude": 13.0569,
        "longitude": 80.2570,
        "email": "dakshin@expressavenue.com",
        "phone": "+91-44-2857-9012",
        "website": "https://dakshin.example.com",
        "address": "Express Avenue Mall, Royapettah, Chennai",
        "city": "Chennai"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Koshy's",
        "location": "St. Marks Road",
        "cuisine": "Continental",
        "total_capacity": 70,
        "opening_time": "08:30",
        "closing_time": "23:00",
        "description": "Heritage restaurant serving continental breakfast, steaks, and old Bangalore charm since 1940.",
        "latitude": 12.9716,
        "longitude": 77.6033,
        "email": "info@koshys.com",
        "phone": "+91-80-2221-3456",
        "website": "https://koshys.example.com",
        "address": "St. Marks Road, Bengaluru",
        "city": "Bengaluru"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Malaka Spice",
        "location": "Koregaon Park",
        "cuisine": "Southeast Asian",
        "total_capacity": 65,
        "opening_time": "12:00",
        "closing_time": "23:30",
        "description": "Authentic Southeast Asian cuisine with Thai, Malaysian, and Indonesian specialties.",
        "latitude": 18.5204,
        "longitude": 73.8567,
        "email": "reservations@malakaspice.com",
        "phone": "+91-20-2615-6789",
        "website": "https://malakaspice.example.com",
        "address": "Lane 5, Koregaon Park, Pune",
        "city": "Pune"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Ohri's Jiva Imperia",
        "location": "Jubilee Hills",
        "cuisine": "Multi-cuisine",
        "total_capacity": 180,
        "opening_time": "12:00",
        "closing_time": "23:00",
        "description": "Upscale multi-cuisine restaurant with Indian, Chinese, and continental dishes.",
        "latitude": 17.4126,
        "longitude": 78.4071,
        "email": "jiva@ohris.com",
        "phone": "+91-40-2354-7890",
        "website": "https://ohris.example.com",
        "address": "Road No. 1, Jubilee Hills, Hyderabad",
        "city": "Hyderabad"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Britannia & Co.",
        "location": "Ballard Estate",
        "cuisine": "Parsi",
        "total_capacity": 40,
        "opening_time": "11:30",
        "closing_time": "16:00",
        "description": "Historic Parsi cafe serving berry pulao, caramel custard, and traditional Irani chai.",
        "latitude": 18.9350,
        "longitude": 72.8422,
        "email": "info@britannia.com",
        "phone": "+91-22-2261-5264",
        "website": "https://britannia.example.com",
        "address": "Wakefield House, Ballard Estate, Mumbai",
        "city": "Mumbai"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Sagar Ratna",
        "location": "Sector 14",
        "cuisine": "South Indian",
        "total_capacity": 100,
        "opening_time": "08:00",
        "closing_time": "22:30",
        "description": "Popular chain serving authentic South Indian breakfast and meals.",
        "latitude": 28.4595,
        "longitude": 77.0266,
        "email": "sector14@sagarratna.com",
        "phone": "+91-124-234-5678",
        "website": "https://sagarratna.example.com",
        "address": "City Centre, Sector 14, Gurgaon",
        "city": "Gurgaon"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Murugan Idli Shop",
        "location": "Besant Nagar",
        "cuisine": "South Indian",
        "total_capacity": 50,
        "opening_time": "06:30",
        "closing_time": "22:00",
        "description": "Famous for soft idlis, crispy vadas, and authentic Tamil Nadu breakfast items.",
        "latitude": 13.0067,
        "longitude": 80.2669,
        "email": "contact@muruganidli.com",
        "phone": "+91-44-2446-7890",
        "website": "https://muruganidli.example.com",
        "address": "Besant Nagar, Chennai",
        "city": "Chennai"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Windmills Craftworks",
        "location": "Whitefield",
        "cuisine": "Continental",
        "total_capacity": 120,
        "opening_time": "12:00",
        "closing_time": "01:00",
        "description": "Microbrewery with craft beers, wood-fired pizzas, and live music performances.",
        "latitude": 12.9698,
        "longitude": 77.7500,
        "email": "info@windmillscraftworks.com",
        "phone": "+91-80-4567-8901",
        "website": "https://windmillscraftworks.example.com",
        "address": "Phoenix MarketCity, Whitefield, Bengaluru",
        "city": "Bengaluru"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Arthur's Theme",
        "location": "Koregaon Park",
        "cuisine": "Continental",
        "total_capacity": 55,
        "opening_time": "19:00",
        "closing_time": "01:00",
        "description": "Elegant fine dining restaurant with continental cuisine and extensive wine collection.",
        "latitude": 18.5314,
        "longitude": 73.8911,
        "email": "reservations@arthurstheme.com",
        "phone": "+91-20-2612-3456",
        "website": "https://arthurstheme.example.com",
        "address": "Lane 7, Koregaon Park, Pune",
        "city": "Pune"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Bawarchi",
        "location": "RTC X Roads",
        "cuisine": "Hyderabadi",
        "total_capacity": 150,
        "opening_time": "11:30",
        "closing_time": "23:00",
        "description": "Famous for authentic Hyderabadi biryani, kebabs, and traditional Deccan cuisine.",
        "latitude": 17.4065,
        "longitude": 78.4772,
        "email": "orders@bawarchi.com",
        "phone": "+91-40-2761-4567",
        "website": "https://bawarchi.example.com",
        "address": "RTC X Roads, Hyderabad",
        "city": "Hyderabad"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Mahesh Lunch Home",
        "location": "Fort",
        "cuisine": "Seafood",
        "total_capacity": 80,
        "opening_time": "12:00",
        "closing_time": "15:30",
        "description": "Iconic seafood restaurant serving Mangalorean fish curry, koliwada prawns, and sol kadhi.",
        "latitude": 18.9320,
        "longitude": 72.8347,
        "email": "info@maheshlunchhome.com",
        "phone": "+91-22-2287-0938",
        "website": "https://maheshlunchhome.example.com",
        "address": "Cawasji Patel Street, Fort, Mumbai",
        "city": "Mumbai"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Barbeque Nation",
        "location": "Sector 29",
        "cuisine": "Barbecue",
        "total_capacity": 200,
        "opening_time": "12:00",
        "closing_time": "23:30",
        "description": "Popular buffet restaurant with live grills on tables and extensive Indian and continental spread.",
        "latitude": 28.4601,
        "longitude": 77.0637,
        "email": "gurgaon@barbequenation.com",
        "phone": "+91-124-456-7891",
        "website": "https://barbequenation.example.com",
        "address": "Leisure Valley, Sector 29, Gurgaon",
        "city": "Gurgaon"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Ponnusamy Hotel",
        "location": "Egmore",
        "cuisine": "Chettinad",
        "total_capacity": 90,
        "opening_time": "11:00",
        "closing_time": "23:00",
        "description": "Authentic Chettinad cuisine with spicy curries, pepper chicken, and traditional Tamil dishes.",
        "latitude": 13.0732,
        "longitude": 80.2609,
        "email": "info@ponnusamyhotel.com",
        "phone": "+91-44-2819-2345",
        "website": "https://ponnusamyhotel.example.com",
        "address": "Egmore High Road, Chennai",
        "city": "Chennai"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Truffles",
        "location": "Koramangala",
        "cuisine": "American",
        "total_capacity": 75,
        "opening_time": "11:00",
        "closing_time": "01:00",
        "description": "Popular American diner serving burgers, steaks, and desserts in a casual setting.",
        "latitude": 12.9352,
        "longitude": 77.6245,
        "email": "koramangala@truffles.com",
        "phone": "+91-80-4123-4567",
        "website": "https://truffles.example.com",
        "address": "Koramangala 5th Block, Bengaluru",
        "city": "Bengaluru"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Shabree",
        "location": "Hinjewadi",
        "cuisine": "Maharashtrian",
        "total_capacity": 110,
        "opening_time": "11:30",
        "closing_time": "22:30",
        "description": "Traditional Maharashtrian thali restaurant with authentic regional specialties.",
        "latitude": 18.5908,
        "longitude": 73.7394,
        "email": "hinjewadi@shabree.com",
        "phone": "+91-20-6789-0123",
        "website": "https://shabree.example.com",
        "address": "Rajiv Gandhi Infotech Park, Hinjewadi, Pune",
        "city": "Pune"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Rayalaseema Ruchulu",
        "location": "Kondapur",
        "cuisine": "Andhra",
        "total_capacity": 140,
        "opening_time": "12:00",
        "closing_time": "22:30",
        "description": "Authentic Andhra cuisine with spicy curries, biryanis, and traditional village-style cooking.",
        "latitude": 17.4569,
        "longitude": 78.3677,
        "email": "kondapur@rayalaseemaruchulu.com",
        "phone": "+91-40-4012-3456",
        "website": "https://rayalaseemaruchulu.example.com",
        "address": "Cyber Towers, Kondapur, Hyderabad",
        "city": "Hyderabad"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Cafe Mocha",
        "location": "Bandra",
        "cuisine": "Continental",
        "total_capacity": 60,
        "opening_time": "09:00",
        "closing_time": "01:00",
        "description": "Trendy cafe with continental dishes, desserts, and specialty coffee in a cozy ambiance.",
        "latitude": 19.0596,
        "longitude": 72.8295,
        "email": "bandra@cafemocha.com",
        "phone": "+91-22-2640-5678",
        "website": "https://cafemocha.example.com",
        "address": "Hill Road, Bandra West, Mumbai",
        "city": "Mumbai"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Haldiram's",
        "location": "Golf Course Road",
        "cuisine": "North Indian",
        "total_capacity": 160,
        "opening_time": "08:00",
        "closing_time": "23:00",
        "description": "Popular chain serving North Indian snacks, sweets, and traditional vegetarian meals.",
        "latitude": 28.4089,
        "longitude": 77.0677,
        "email": "golfcourse@haldirams.com",
        "phone": "+91-124-567-8901",
        "website": "https://haldirams.example.com",
        "address": "Golf Course Road, Sector 56, Gurgaon",
        "city": "Gurgaon"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Anjappar",
        "location": "Anna Nagar",
        "cuisine": "Chettinad",
        "total_capacity": 95,
        "opening_time": "11:30",
        "closing_time": "23:00",
        "description": "Renowned Chettinad restaurant chain famous for spicy non-vegetarian dishes and biryanis.",
        "latitude": 13.0850,
        "longitude": 80.2101,
        "email": "annanagar@anjappar.com",
        "phone": "+91-44-2615-7890",
        "website": "https://anjappar.example.com",
        "address": "2nd Avenue, Anna Nagar, Chennai",
        "city": "Chennai"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "The Fatty Bao",
        "location": "Indiranagar",
        "cuisine": "Asian",
        "total_capacity": 85,
        "opening_time": "12:00",
        "closing_time": "01:00",
        "description": "Modern Asian gastro bar serving dim sums, baos, and creative cocktails.",
        "latitude": 12.9719,
        "longitude": 77.6412,
        "email": "indiranagar@thefattybao.com",
        "phone": "+91-80-4567-8902",
        "website": "https://thefattybao.example.com",
        "address": "100 Feet Road, Indiranagar, Bengaluru",
        "city": "Bengaluru"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Vaishali",
        "location": "FC Road",
        "cuisine": "South Indian",
        "total_capacity": 70,
        "opening_time": "07:30",
        "closing_time": "22:30",
        "description": "Iconic Pune restaurant serving South Indian breakfast, snacks, and filter coffee since 1973.",
        "latitude": 18.5089,
        "longitude": 73.8278,
        "email": "info@vaishali.com",
        "phone": "+91-20-2543-6789",
        "website": "https://vaishali.example.com",
        "address": "Fergusson College Road, Pune",
        "city": "Pune"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Shah Ghouse",
        "location": "Tolichowki",
        "cuisine": "Hyderabadi",
        "total_capacity": 120,
        "opening_time": "11:00",
        "closing_time": "01:00",
        "description": "Late-night favorite for authentic Hyderabadi biryani, haleem, and kebabs.",
        "latitude": 17.3616,
        "longitude": 78.4322,
        "email": "orders@shahghouse.com",
        "phone": "+91-40-2313-4567",
        "website": "https://shahghouse.example.com",
        "address": "Tolichowki, Hyderabad",
        "city": "Hyderabad"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Leopold Cafe",
        "location": "Colaba",
        "cuisine": "Continental",
        "total_capacity": 100,
        "opening_time": "08:00",
        "closing_time": "00:30",
        "description": "Historic cafe serving continental breakfast, steaks, and cold beer since 1871.",
        "latitude": 18.9220,
        "longitude": 72.8310,
        "email": "info@leopoldcafe.com",
        "phone": "+91-22-2202-0131",
        "website": "https://leopoldcafe.example.com",
        "address": "Causeway, Colaba, Mumbai",
        "city": "Mumbai"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Cyber Hub Social",
        "location": "Cyber Hub",
        "cuisine": "Multi-cuisine",
        "total_capacity": 180,
        "opening_time": "12:00",
        "closing_time": "01:30",
        "description": "Trendy co-working cafe with global cuisine, craft cocktails, and vibrant atmosphere.",
        "latitude": 28.4950,
        "longitude": 77.0890,
        "email": "cyberhub@socialoffline.in",
        "phone": "+91-124-678-9012",
        "website": "https://socialoffline.example.com",
        "address": "Cyber Hub, DLF Phase 2, Gurgaon",
        "city": "Gurgaon"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Mathsya",
        "location": "Besant Nagar",
        "cuisine": "Seafood",
        "total_capacity": 65,
        "opening_time": "12:00",
        "closing_time": "23:00",
        "description": "Coastal cuisine specialist with fresh catch of the day and traditional Tamil seafood preparations.",
        "latitude": 13.0001,
        "longitude": 80.2707,
        "email": "reservations@mathsya.com",
        "phone": "+91-44-2491-2345",
        "website": "https://mathsya.example.com",
        "address": "Elliot's Beach Road, Besant Nagar, Chennai",
        "city": "Chennai"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Smoke House Deli",
        "location": "UB City Mall",
        "cuisine": "Continental",
        "total_capacity": 90,
        "opening_time": "12:00",
        "closing_time": "01:00",
        "description": "European-style deli with artisanal sandwiches, salads, and gourmet coffee.",
        "latitude": 12.9716,
        "longitude": 77.6033,
        "email": "ubcity@smokehousedeli.com",
        "phone": "+91-80-2567-8901",
        "website": "https://smokehousedeli.example.com",
        "address": "UB City Mall, Vittal Mallya Road, Bengaluru",
        "city": "Bengaluru"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Dario's",
        "location": "Baner",
        "cuisine": "Italian",
        "total_capacity": 75,
        "opening_time": "12:00",
        "closing_time": "23:30",
        "description": "Authentic Italian restaurant with wood-fired pizzas, fresh pasta, and imported ingredients.",
        "latitude": 18.5679,
        "longitude": 73.7797,
        "email": "baner@darios.com",
        "phone": "+91-20-2729-3456",
        "website": "https://darios.example.com",
        "address": "Baner Road, Pune",
        "city": "Pune"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Chutneys",
        "location": "Banjara Hills",
        "cuisine": "South Indian",
        "total_capacity": 110,
        "opening_time": "07:00",
        "closing_time": "22:30",
        "description": "Popular South Indian chain known for variety of dosas, uttapams, and authentic filter coffee.",
        "latitude": 17.4239,
        "longitude": 78.4738,
        "email": "banjarahills@chutneys.com",
        "phone": "+91-40-2354-6789",
        "website": "https://chutneys.example.com",
        "address": "Road No. 12, Banjara Hills, Hyderabad",
        "city": "Hyderabad"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Indigo",
        "location": "Colaba",
        "cuisine": "European",
        "total_capacity": 55,
        "opening_time": "19:00",
        "closing_time": "01:00",
        "description": "Upscale European restaurant with contemporary cuisine and elegant ambiance.",
        "latitude": 18.9067,
        "longitude": 72.8147,
        "email": "reservations@indigorestaurant.com",
        "phone": "+91-22-6636-8999",
        "website": "https://indigorestaurant.example.com",
        "address": "Mandlik Marg, Colaba, Mumbai",
        "city": "Mumbai"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Punjabi By Nature",
        "location": "Ambience Mall",
        "cuisine": "Punjabi",
        "total_capacity": 140,
        "opening_time": "12:00",
        "closing_time": "23:30",
        "description": "Vibrant Punjabi restaurant with live dhol performances, butter chicken, and lassi.",
        "latitude": 28.5021,
        "longitude": 77.1025,
        "email": "ambience@punjabibynature.com",
        "phone": "+91-124-789-0123",
        "website": "https://punjabibynature.example.com",
        "address": "Ambience Mall, Vasant Kunj, Gurgaon",
        "city": "Gurgaon"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Buhari",
        "location": "Anna Salai",
        "cuisine": "Multi-cuisine",
        "total_capacity": 130,
        "opening_time": "11:00",
        "closing_time": "23:00",
        "description": "Historic restaurant chain serving biryani, Chinese, and continental dishes since 1951.",
        "latitude": 13.0569,
        "longitude": 80.2570,
        "email": "annasalai@buhari.com",
        "phone": "+91-44-2852-4567",
        "website": "https://buhari.example.com",
        "address": "Anna Salai, Chennai",
        "city": "Chennai"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Arbor Brewing Company",
        "location": "Rajajinagar",
        "cuisine": "Continental",
        "total_capacity": 160,
        "opening_time": "12:00",
        "closing_time": "01:00",
        "description": "Microbrewery with craft beers, wood-fired pizzas, and American-style pub food.",
        "latitude": 12.9893,
        "longitude": 77.5553,
        "email": "rajajinagar@arborbrewing.com",
        "phone": "+91-80-3456-7890",
        "website": "https://arborbrewing.example.com",
        "address": "Rajajinagar, Bengaluru",
        "city": "Bengaluru"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Cafe Goodluck",
        "location": "Deccan Gymkhana",
        "cuisine": "Irani",
        "total_capacity": 50,
        "opening_time": "06:00",
        "closing_time": "23:30",
        "description": "Heritage Irani cafe serving bun maska, Irani chai, and mutton kheema since 1935.",
        "latitude": 18.5158,
        "longitude": 73.8567,
        "email": "info@cafegoodluck.com",
        "phone": "+91-20-2567-1234",
        "website": "https://cafegoodluck.example.com",
        "address": "Deccan Gymkhana, Pune",
        "city": "Pune"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Minerva Coffee Shop",
        "location": "King Koti",
        "cuisine": "South Indian",
        "total_capacity": 80,
        "opening_time": "06:30",
        "closing_time": "22:00",
        "description": "Traditional coffee shop serving South Indian breakfast, filter coffee, and snacks since 1956.",
        "latitude": 17.4126,
        "longitude": 78.4772,
        "email": "kingkoti@minervacoffee.com",
        "phone": "+91-40-2323-4567",
        "website": "https://minervacoffee.example.com",
        "address": "King Koti Road, Hyderabad",
        "city": "Hyderabad"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Bastian",
        "location": "Linking Road",
        "cuisine": "Seafood",
        "total_capacity": 70,
        "opening_time": "12:00",
        "closing_time": "01:00",
        "description": "Contemporary seafood restaurant with fresh catch, innovative preparations, and craft cocktails.",
        "latitude": 19.0544,
        "longitude": 72.8181,
        "email": "reservations@bastian.in",
        "phone": "+91-22-2600-9999",
        "website": "https://bastian.example.com",
        "address": "Linking Road, Bandra West, Mumbai",
        "city": "Mumbai"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Karim's",
        "location": "Sector 14",
        "cuisine": "Mughlai",
        "total_capacity": 100,
        "opening_time": "12:00",
        "closing_time": "23:00",
        "description": "Famous Mughlai restaurant chain serving authentic kebabs, biryanis, and traditional curries.",
        "latitude": 28.4595,
        "longitude": 77.0266,
        "email": "gurgaon@karims.com",
        "phone": "+91-124-890-1234",
        "website": "https://karims.example.com",
        "address": "Old Delhi Road, Sector 14, Gurgaon",
        "city": "Gurgaon"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Cream Centre",
        "location": "T. Nagar",
        "cuisine": "Vegetarian",
        "total_capacity": 85,
        "opening_time": "11:00",
        "closing_time": "23:00",
        "description": "Popular vegetarian restaurant chain with Indian, Chinese, and continental dishes.",
        "latitude": 13.0418,
        "longitude": 80.2341,
        "email": "tnagar@creamcentre.com",
        "phone": "+91-44-2434-5678",
        "website": "https://creamcentre.example.com",
        "address": "Pondy Bazaar, T. Nagar, Chennai",
        "city": "Chennai"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Monkey Bar",
        "location": "Indiranagar",
        "cuisine": "Continental",
        "total_capacity": 120,
        "opening_time": "12:00",
        "closing_time": "01:30",
        "description": "Gastropub with global cuisine, craft cocktails, and quirky interiors.",
        "latitude": 12.9719,
        "longitude": 77.6412,
        "email": "indiranagar@monkeybar.in",
        "phone": "+91-80-4890-1234",
        "website": "https://monkeybar.example.com",
        "address": "100 Feet Road, Indiranagar, Bengaluru",
        "city": "Bengaluru"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Kayani Bakery",
        "location": "East Street",
        "cuisine": "Bakery",
        "total_capacity": 30,
        "opening_time": "07:30",
        "closing_time": "20:00",
        "description": "Heritage Parsi bakery famous for Shrewsbury biscuits, mawa cakes, and fresh bread.",
        "latitude": 18.5196,
        "longitude": 73.8553,
        "email": "info@kayanibakery.com",
        "phone": "+91-20-2633-2525",
        "website": "https://kayanibakery.example.com",
        "address": "East Street, Camp, Pune",
        "city": "Pune"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Jewel of Nizam",
        "location": "Himayatnagar",
        "cuisine": "Hyderabadi",
        "total_capacity": 90,
        "opening_time": "12:00",
        "closing_time": "23:30",
        "description": "Royal Hyderabadi cuisine with traditional dum biryani, haleem, and Nizami specialties.",
        "latitude": 17.4065,
        "longitude": 78.4772,
        "email": "reservations@jewelofnizam.com",
        "phone": "+91-40-2763-4567",
        "website": "https://jewelofnizam.example.com",
        "address": "Himayatnagar, Hyderabad",
        "city": "Hyderabad"
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Soam",
        "location": "Mahim",
        "cuisine": "Gujarati",
        "total_capacity": 60,
        "opening_time": "12:00",
        "closing_time": "15:30",
        "description": "Authentic Gujarati thali restaurant with traditional dal, kadhi, and seasonal vegetables.",
        "latitude": 19.0410,
        "longitude": 72.8420,
        "email": "mahim@soam.com",
        "phone": "+91-22-2444-9999",
        "website": "https://soam.example.com",
        "address": "Mahim Causeway, Mumbai",
        "city": "Mumbai"
    }
]

def main():
    print("Starting to populate restaurants...")
    
    # Create the database directory if it doesn't exist
    db_dir = Path(__file__).parent / "data"
    db_dir.mkdir(exist_ok=True)
    
    successful = 0
    already_exists = 0
    failed = 0
    
    for restaurant in restaurants:
        # Check if a restaurant with the same name already exists
        existing_restaurants = [r for r in get_restaurant_by_name(restaurant["name"])]
        
        if existing_restaurants:
            print(f"Restaurant '{restaurant['name']}' already exists. Skipping...")
            already_exists += 1
            continue
            
        try:
            add_restaurant(restaurant)
            print(f"Added restaurant: {restaurant['name']} ({restaurant['cuisine']})")
            successful += 1
        except Exception as e:
            print(f"Failed to add restaurant {restaurant['name']}: {str(e)}")
            failed += 1
    
    print(f"\nSummary:")
    print(f"Successfully added: {successful} restaurants")
    print(f"Already existing: {already_exists} restaurants")
    print(f"Failed to add: {failed} restaurants")

def get_restaurant_by_name(name):
    """Helper function to check if a restaurant with the given name exists"""
    from app.db.database import get_connection
    
    with get_connection() as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM restaurants WHERE name = ?", (name,))
        return cursor.fetchall()

if __name__ == "__main__":
    main()
